### ISSUE TITLE
Using a different company's USB.idVendor incorrectly.

### ISSUE THREAD

**Issue by askn37** [microchip-pic-avr-examples/avr64du32-keypad-mplab-mcc#1]
I think this idVendor is a mistake for 0x4D8.

https://github.com/microchip-pic-avr-examples/avr64du32-keypad-mplab-mcc/blob/0bd6fcb0a748cc7b46b895fb61e935d51e45a93a/avr64du32-keypad-mplab-mcc.X/mcc_generated_files/usb/usb_descriptors.c#L83

https://the-sz.com/products/usbid/index.php?v=0x4d7&p=&n=

**Comment by pic-avr-github-admin** [comment]
Thank you for your report,
I've updated the example to the correct VID. The fix applies to versions >= v1.1.0
